[package]
name = "mwa_hyperbeam"
version = "0.2.1"
authors = ["Marcin Sokolowski <marcin.sokolowski@curtin.edu.au",
           "Christopher H. Jordan <christopherjordan87@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = []
python = ["pyo3", "numpy"]

[profile.release]
lto = true
codegen-units = 1   # Set this to 1 in Cargo.toml to allow for maximum size reduction optimizations

# Make a rust library, as well as static and C-compatible dynamic libraries
# available as "libmwa_hyperbeam.a" and "libmwa_hyperbeam.so".
[lib]
crate-type = ["rlib", "staticlib", "cdylib"]

[dependencies]
dashmap = "3.11.*"
hdf5 = "0.7.*"
ndarray = "0.13.*"
num = "0.3.*"
rayon = "1.*"
thiserror = "1.0.*"

pyo3 = { version = "0.12.*", features = ["extension-module"], optional = true }
numpy = { version = "0.12.*", optional = true }

[dev-dependencies]
anyhow = "1.0.*"
approx = "0.4.*"
criterion = "0.3.*"
serial_test = "0.5.*"
structopt = "0.3.*"

[build-dependencies]
cbindgen = "*"

[[bench]]
name = "bench"
harness = false
