[tasks.linux_apt_get_update]
command = "sudo"
args = ["apt-get", "update"]

[tasks.linux_install_deps]
script = """
sudo apt-get -y update
sudo apt-get install -y libhdf5-dev liberfa-dev
"""

[tasks.mac_install_deps]
script = """
# 1.12 doesn't work?
brew install hdf5@1.10
wget https://github.com/MWATelescope/homebrew-tap/releases/download/v2021.07.20.10.17/erfa--2.0.0.catalina.bottle.1.tar.gz -O erfa--2.0.0.catalina.bottle.1.tar.gz
brew install -f erfa--2.0.0.catalina.bottle.1.tar.gz
"""

[tasks.install_deps]
linux_alias = "linux_install_deps"
mac_alias = "mac_install_deps"

[tasks.check]
command = "cargo"
args = ["check"]

[tasks.format_fix]
command = "cargo"
args = ["fmt", "--", "--emit=files"]
install_crate = "rustfmt"

[tasks.format_check]
command = "cargo"
args = ["fmt", "--all", "--", "--check"]
install_crate = "rustfmt"

[tasks.clippy]
command = "cargo"
args = ["clippy", "--", "-D", "warnings"]
install_crate = "clippy"

[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.build_clean]
command = "cargo"
args = ["build"]
dependencies = ["clean"]

[tasks.test]
command = "cargo"
args = ["test"]

[tasks.ci]
dependencies = [
  "check",
  "format_check",
  "clippy",
]

[tasks.pre_commit]
dependencies = [
  "format_fix",
  "test",
]
