[project]
name = "mwa_hyperbeam"
repository = "https://github.com/MWATelescope/mwa_hyperbeam"
requires-python = ">=3.7"
dependencies = ["numpy"]

[build-system]
requires = ["setuptools", "python_version>='3.7'"]
build-backend = "maturin"
