---
name: Generate Coverage report

# Based on https://github.com/actions-rs/meta/blob/master/recipes/quickstart.md

# Do this on every push that isn't tagged
on:
  push:
    tags-ignore:
      - '**'
    branches:
    - '**'
  pull_request:

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: llvm-tools-preview

      - name: Install dependencies
        run: |
          sudo apt update -y
          sudo apt install -y \
            tzdata \
            build-essential \
            pkg-config \
            cmake \
            curl \
            git \
            lcov \
            liberfa-dev \
            libhdf5-dev \
            ;
          curl -LsSf https://github.com/taiki-e/cargo-llvm-cov/releases/latest/download/cargo-llvm-cov-x86_64-unknown-linux-gnu.tar.gz | tar xzf - -C ~/.cargo/bin
        env:
          DEBIAN_FRONTEND: noninteractive

      - name: Get the HDF5 file
        run: curl http://ws.mwatelescope.org/static/mwa_full_embedded_element_pattern.h5 -o mwa_full_embedded_element_pattern.h5

      - name: Generate test lcov coverage into coverage/ dir
        run: |
          mkdir -p coverage
          cargo llvm-cov --all --lcov --output-path coverage/coverage.lcov
          # this uses the result of the previous run to generate a text summary
          cargo llvm-cov --no-run
        env:
          MWA_BEAM_FILE: mwa_full_embedded_element_pattern.h5

      - name: Upload reports to codecov.io
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
