---
name: Generate Coverage report

# Do this on every push that isn't tagged
on:
  push:
    tags-ignore:
      - '**'
    branches:
      - '**'
  pull_request:

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0
  DEBIAN_FRONTEND: noninteractive
  MWA_BEAM_FILE: mwa_full_embedded_element_pattern.h5

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
          components: llvm-tools-preview

      - name: Install dependencies
        run: |
          sudo apt -y update
          sudo apt -y install libhdf5-dev liberfa-dev

      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov

      - name: Get the HDF5 file
        run: curl http://ws.mwatelescope.org/static/mwa_full_embedded_element_pattern.h5 -o mwa_full_embedded_element_pattern.h5

      - name: Generate code coverage
        run: cargo llvm-cov --workspace --lcov --output-path lcov.info

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: lcov.info
          fail_ci_if_error: true
