# this tests that the latest docker image works, and does linter checks
# linter checks happen here because docker images are faster than waiting for
# dependencies to install on GitHub Actions VMs
on: [push, pull_request]

name: Docker Tests

jobs:
  # TODO: make build, test and push separate steps, push depend on test
  push:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: mwatelescope/hyperbeam:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
  check:
    name: Docker Test and Release
    # todo needs: build
    needs: push
    runs-on: ubuntu-latest
    container: mwatelescope/hyperbeam:latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
          components: rustfmt, clippy
      - run: cargo check
      - run: cargo fmt --all -- --check
      - run: cargo clippy --all-targets --all-features -- -D warnings
      - run: cargo test --release
      - run: cargo test --no-default-features --release --features=cli