---
name: Cross-platform tests

# Do this on every push that isn't tagged
on:
  push:
    tags-ignore:
      - '**'
    branches:
    - '**'
  pull_request:

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0

jobs:
  test:
    name: Test ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        include:
          - os: macos-latest
            python-version: [3.7, 3.8, 3.9, 3.10]
    steps:
    - name: Checkout sources
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Install stable toolchain
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true

    - name: Install Cargo Make
      uses: davidB/rust-cargo-make@v1

    - name: Install Dependencies
      run: cargo make install_deps

    - name: Get the HDF5 file
      run: curl http://ws.mwatelescope.org/static/mwa_full_embedded_element_pattern.h5 -o mwa_full_embedded_element_pattern.h5

    - name: Run cargo check, fmt, clippy
      run: cargo make ci

    - name: No CUDA references in CPU-only header
      run: |
        ! grep -i cuda include/mwa_hyperbeam.h

    - name: Run tests
      run: cargo test

    - name: Minimum-specified Rust version works
      run: |
        MIN_RUST=$(grep -m1 "rust-version" Cargo.toml | sed 's|.*\"\(.*\)\"|\1|')
        rustup install $MIN_RUST --profile minimal
        cargo clean
        cargo +${MIN_RUST} test
