---
name: Cross-platform tests

# Do this on every push
on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Test ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        include:
          - os: macos-latest
            python-version: [3.6, 3.7, 3.8, 3.9]
    steps:
    - name: Checkout sources
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Install stable toolchain
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true

    - name: Install Cargo Make
      uses: davidB/rust-cargo-make@v1

    - name: Install Dependencies
      run: cargo make install_deps

    - name: Get the HDF5 file
      run: curl http://ws.mwatelescope.org/static/mwa_full_embedded_element_pattern.h5 -o mwa_full_embedded_element_pattern.h5

    - name: Run cargo check, fmt, clippy
      run: cargo make ci

    - name: Run tests
      run: cargo make test
