---
name: Tests

# Do this on every push
on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout sources
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Install dependencies
      run: |
          sudo apt update -y
          DEBIAN_FRONTEND="noninteractive" sudo apt-get -y install tzdata
          sudo apt install -y curl libhdf5-dev

    - name: Install stable toolchain
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true

    - name: Get the HDF5 file
      run: curl http://ws.mwatelescope.org/static/mwa_full_embedded_element_pattern.h5 -o mwa_full_embedded_element_pattern.h5

    - name: Run tests
      run: |
        cargo test
